### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by crjeder** [cmcornish/Pico-Green-Clock#9]
Here is the error:
```
In file included from /home/---/pico/pico-sdk/lib/lwip/src/include/lwip/opt.h:51,
                 from /home/---/pico/pico-sdk/lib/lwip/src/include/lwip/apps/httpd_opts.h:44,
                 from /home/---/pico/pico-sdk/lib/lwip/src/apps/http/fs.c:33:
/home/---/pico/Pico-Green-Clock/lwipopts.h:96:27: fatal error: htmldata.c: No such file or directory
   96 | #define HTTPD_FSDATA_FILE "htmldata.c"
      |                           ^~~~~~~~~~~~
compilation terminated.
```

**Comment by cmcornish** [comment]
Hello crjeder,

This file is created by the perl script called by the cmake process. I use the windows toolchain - I've not tried any other method.
The CMakeLists.txt file line 25 generates this file as part of the build process - does this part run for you?

Cheers,
cmcornish

**Comment by crjeder** [comment]
Ok, I had some time to dig into this. Have switched to VS on Win11 because that's the official supported install. It did not help but I've added ``${PICO_SDK_PATH}/src/rp2_common/pico_cyw43_arch/include`` to the target_include_directories.
Thanks for your support and maintaining this great software!

**Comment by cmcornish** [comment]
Thanks crjeder. Do I need to make any changes to the code or add this into the README.md file? If so, what text changes would you recommend?

**Comment by crjeder** [comment]
If you don't mind I'd do a PR. Would change only the CMakeList.txt
